name: Publish
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: npx jsr publish
